---

  - name: Clones efl repo and compiles it from source
    hosts: local
    user: "{{ user }}"
    sudo: no

    tasks:


      - name: clones efl repo
        git: repo=http://git.enlightenment.org/core/efl.git dest=/home/{{user}}/enlight/efl
